### ISSUE TITLE
add testimonials page (v3)

### ISSUE THREAD

**Issue by ofZach** [SFPC/sfpc.github.io#61]
quote from people.  will be really nice

**Comment by caseyg** [comment]
Check out the branch above, #83, I thought it would make a lot of sense to put testimonials as a sidebar on the participate page, under the heading Alumni <3 SFPC.

Right now we only have 7 testimonials, so they all fit there. Maybe when we get more it will make sense to give them a dedicated page? Or let me know if you want to have them on their own page now? 

Otherwise we can close this when we merge the `apply-inline` branch.
