### ISSUE TITLE
Fall 13 names

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#94]
http://sfpc.io/people/#filter=.fall-2013
this shows fall 2015 students as well

**Comment by caseyg** [comment]
Can you post a screenshot? I can't replicate this.

![screen shot 2015-03-17 at 1 20 15 pm](https://cloud.githubusercontent.com/assets/462020/6693326/9acddc14-cca8-11e4-8aff-2550c7cc1893.png)

I think it's just slow to load all images of everybody ever and _then_ filter to Fall 13.

At a certain scale, there's not an easy way to make a single page of a million images load fast. So I've been thinking that instead of dynamic filtering that loads everything and whooshes it around, we should just make Jekyll generate the filter pages for each class:

/people/fall-2015
/people/spring-2015
/people/teachers

It'd be probably be an hour or two of my time, if that sounds like a better solution.

**Comment by poohlaga** [comment]
fixed fixed
